### PR TITLE
Fix force accept of invalid consignments

### LINKED ISSUE #24: transfer accept succeeds even if transaction has not been confirmed
Using our `rgb-sandbox` I have tried accepting transfers for which the anchoring transaction has not been confirmed and it unexpectedly succeeds.

I expected the `accept` operation to return a failure instead, as the `--force` option is not provided.

I have prepared a modified version of the sandbox in this [branch](https://github.com/nicbus/rgb-sandbox/tree/v0.10_noconf) to reproduce the condition. Running the `demo.sh` script with the `--noconf` option disables mining after broadcasting the transfer transactions. This can be confirmed e.g. by looking at bitcoind logs while the script is running (`docker compose logs
-f bitcoind`).

### PR DESCRIPTION
**Pull request by dr-orlovsky**
Closes #24

### CODE REVIEW

**Comment by zoedberg** [comment]
I tried this PR on the sandbox branch mentioned in #24, and it seems this fix is not enough to solve the issue.
Looking to the code I noticed that `unmined_terminals` (the vector in `Status` that if not empty brings to `Validity::UnminedTerminals`) gets filled only in this piece of code:
```rust
for (operation, _) in &self.end_transitions {
    if let Some(anchor) = self.anchor_index.get(&operation.id()) {
        if let Some(pos) = self
            .status
            .failures
            .iter()
            .position(|f| f == &Failure::SealNoWitnessTx(anchor.txid))
        {
            self.status.failures.remove(pos);
            self.status
                .unresolved_txids
                .retain(|txid| *txid != anchor.txid);
            self.status.unmined_terminals.push(anchor.txid);
            self.status
                .warnings
                .push(Warning::TerminalWitnessNotMined(anchor.txid));
        }
    }
}
```
so only if a `Failure::SealNoWitnessTx` is found. But looking to `Failure::SealNoWitnessTx` documentation I've noticed it says `witness transaction {0} is not known to the transaction resolver.`.

This explains why in the sandbox the validation status results in:
```
Consignment has non-mined terminal(s)
Non-mined terminals:
- e348c9b3d541ac5a4b1f4e796068352e20c8ef0b967ed771951771b7597150f4
Validation warnings:
- terminal witness transaction e348c9b3d541ac5a4b1f4e796068352e20c8ef0b967ed771951771b7597150f4 is not yet mined.
```
when we validate the consignment before broadcasting the TX, while after broadcasting the TX (not mining any block afterwards) the validation status becomes:
```
Consignment is valid
```

If I didn't misunderstand the meaning of `Validity::UnminedTerminals` this warning should be present also when the transaction is in the mempool but is unmined. If so I think this PR is not enough to close #24

**Comment by dr-orlovsky** [comment]
Consignment is valid whenever resolver returns transaction given tx id. RGB has not concept of mempool. You just need to write resolver that wouldn't return tx until it is mined or has 3 confirmations - whatever the wallet policy is.

**Comment by zoedberg** [comment]
I find naming a bit confusing then. `Validity::UnminedTerminals` makes the developer think that terminals have not been mined (which means they have no confirmations). Maybe a less ambiguous name would be `UnresolvedTerminals`. And `Validity::UnresolvedTransactions` would be less confusing if named `UnresolvedNonTerminals`.

**Comment by dr-orlovsky** [comment]
We can't change names without breaking API changes, thus it must be an independent PR targeting v0.11. Thus this PR hsould be merged first even if we will change the names after.

**Review by zoedberg — APPROVED** [review]

**Pull request merged**
