### PR TITLE
electrum: add safety margins for tx height check

### PR DESCRIPTION
**Pull request by zoedberg**
as discussed on telegram, this PR implements @adambor proposal to add a safety margin

### CODE REVIEW

**Review by dr-orlovsky — COMMENTED** [review]
It is very much a non-rust-way... Pls review my commit on top: f69200e36f1fa7ea2b9ebc34f6b8f061b1b5be1f

**Comment by zoedberg** [comment]
Your version is rustier, sure. I'm just not sure the logic is now the same, since you start first iteration from `1` (instead of `0`, as before), shouldn't that go to `forward + 2` (instead of `forward + 1`, as before)?

**Comment by dr-orlovsky** [comment]
> since you start first iteration from 1 (instead of 0, as before), shouldn't that go to forward + 2 (instead of forward + 1, as before)?

It is not about the number of iterations - it is about the maximum we need to check for.

Before, we were going for as many blocks as we knew to be mined: that is `forward` blocks from the head. So the previous code was actually needlessly checking until `min_header + 1 - confirmations + new_bloc_count + 1`, and the last `1` was unnecessary.

**Comment by zoedberg** [comment]
> > since you start first iteration from 1 (instead of 0, as before), shouldn't that go to forward + 2 (instead of forward + 1, as before)?
> 
> It is not about the number of iterations - it is about the maximum we need to check for.
> 
> Before, we were going for as many blocks as we knew to be mined: that is `forward` blocks from the head. So the previous code was actually needlessly checking until `min_header + 1 - confirmations + new_bloc_count + 1`, and the last `1` was unnecessary.

With the last commit you removed the `+ 1` from the initial height calculation, so to keep the code looping from min to max + 1 you should do forward + 2

**Comment by zoedberg** [comment]
with last commit (ce75db2c62673d70f79bb739d1196b1d8b75d25d) you fixed the tx height calculation (that previously was looking for the tx from min block height - 1 to max block height, instead of max block height + 1).

just a note though, the comment `// first check from expected min to max height, then max + 1 and finally min - 1` is correct only because `SAFETY_MARGIN` is set to `1`, because now code has been changed in a way that if we increase that variable we will check max + 1, then min - 1, then max + 2, then min - 2 and so on. so maybe we should update the comment?

**Pull request merged**
