### PR TITLE
Fix wasm compilation

### PR DESCRIPTION
**Pull request by crisdut**

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
This will not pass CI and break a lot of compile variants. Since you did the PR agains v0.11 CI doesn't run; I changed it to be against the master branch. Let's see the errors.

Overall I do not understand why you need this since `rgb` crate is a command-line tool which should not be used from WASM. You have other lower-level libraries for that...

**Comment by dr-orlovsky** [comment]
@crisdut and please can you do this just as a branch with a single last commit and not on top of other PR? They are unrelated.

**Comment by crisdut** [comment]
> This will not pass CI and break a lot of compile variants. Since you did the PR agains v0.11 CI doesn't run; I changed it to be against the master branch. Let's see the errors.

Ok, I will check.

> Overall I do not understand why you need this since `rgb` crate is a command-line tool which should not be used from WASM. You have other lower-level libraries for that...

In fact, I left the CLI optional, precisely so as not to use it in WASM, since all PSBT and payment modules are contained in rgb_rt, to avoid having to copy and paste the entire library into bitmask-core.

**Comment by dr-orlovsky** [comment]
I think the right way of fixing this is this one: https://github.com/BP-WG/bp-wallet/pull/15/commits/9d1cf14c1a3c6810827f1de9b887103f3f178ac8

We have discussion on the same matter here: https://github.com/RGB-WG/rgb/pull/128#pullrequestreview-1878202745

**Pull request closed without merging**
