### PR TITLE
Remove beneficiary in transfer step

### LINKED ISSUE #69: Wrong beneficiary in rgb transfer step
### **Description**
**Version:** https://github.com/RGB-WG/rgb/pull/39/commits/62b5009146b363553493e2a3a9b516866f54c78c

When we try running the transfer command below, the cli returns: `Error: taproot output doesn't specify internal key.` 

```
rgb  -w default transfer rgb:28hM4....f86n 100 ./transfer.rgb
```

After investigate, I noticed that the transfer step mistakenly uses the invoice beneficiary, transferring all the satoshis to him, which ends up producing an incorrect output in the PSBT. 

**Type:** bug

### PR DESCRIPTION
**Pull request by crisdut**
Closes #69

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
Why do you think we do not need it?

**Comment by dr-orlovsky** [comment]
Ok, I see: https://github.com/RGB-WG/rgb/issues/69

But we need beneficiary to support pay-to-address invoices. The fix should be different, I will work on it

**Comment by crisdut** [comment]
> But we need beneficiary to support pay-to-address invoices. The fix should be different, I will work on it

Yes you are right.

We can provide an optional parameter on the command line to place pay-to-address (in the format `address:sats`, for example).

**Comment by dr-orlovsky** [comment]
Not sure I understand. Pay-to-address is the feature of invoice. That is why we have this `Beneficiary` type there.

**Comment by crisdut** [comment]
> Not sure I understand. Pay-to-address is the feature of invoice. That is why we have this `Beneficiary` type there.

Ok, sure.

I use the following command to transfer rgb:

```
rgb transfer rgb:Q5.../RGB20/100+utxob:VthYavx-gTG3Axu6v-W4Z5eCRsX-uALkB9Jin-4zhGZY1Aq-6kxZjV 1000
```

This command constructs the new **psbt** and **consigment** files. But, inside of the method `Runtime::construct_psbt,` we invoke another method called `Wallet::construct_psbt,`, and in this method, we pass any address from our wallet as the beneficiary. The problem with this is that all satoshi is being drained to this new address, and it ends up that the PSBT generated does not produce a change output, which is the prerequisite for RGB. 
  
The solution I thought of now seems incomplete, I will think more to resolve this issue.

**Comment by dr-orlovsky** [comment]
Yes, I understood the issue, thank you for finding it. The solution is to allocate specific amount of sats to that beneficiary - that's it. I will do that.

**Comment by dr-orlovsky** [comment]
Closing since the PR is invalid and the problem was caused by a different reason: https://github.com/RGB-WG/rgb/issues/69#issuecomment-1868636430

**Pull request closed without merging**
