### PR TITLE
Fix Windows builds in CI

### PR DESCRIPTION
**Pull request by zoedberg**
This will fix the windows build on the CI by adding nasm as a dependency

### CODE REVIEW

**Comment by zoedberg** [comment]
I'm looking for a solution for the `wasm-testing` job, please don't merge this in the meantime

**Comment by zoedberg** [comment]
I've opened https://github.com/BP-WG/bp-esplora-client/pull/8 and add a commit here to fix the wasm build (I'll change the git dependency after the PR gets merged or I'll remove it if you release a new version of bp-esplora-client). Unfortunately there's no way to conditionally exclude dependencies based on target, so I had to add a dedicated feature for wasm. Moreover `wasm-pack` doesn't seem to provide a way to select features (it uses the default ones), so I had to remove all default features from here. CI is still failing because of some missing feature gates (unnoticed because of the default features), I will fix this tomorrow or in the following days

**Comment by dr-orlovsky** [comment]
> there's no way to conditionally exclude dependencies based on target

There is:

```toml
[target.'cfg(target_arch = "wasm32")'.dependencies]
# your dependencies
```

**Comment by zoedberg** [comment]
Sorry, I meant features, not dependencies. I've found this related open issue https://github.com/rust-lang/cargo/issues/1197 so it seems it's not possible at the moment

**Comment by zoedberg** [comment]
@dr-orlovsky all CI jobs pass, IMO this can be merged

**Review by dr-orlovsky — APPROVED** [review]
ACK 8ceff54c4f7cf7b67d4c82aeefbd454e56e6c6d5

**Pull request merged**
