### PR TITLE
Rename esplora into esplora_blocking and do a dedicated resolver module

### PR DESCRIPTION
**Pull request by dr-orlovsky**

### CODE REVIEW

**Review by crisdut — CHANGES_REQUESTED** [review]
Please, change these dependencies:

```toml
bp-wallet = { version = "0.11.0-beta.4", default-features = false, features = ["fs", "serde"] }
bp-esplora = { version = "0.11.0-beta.2", default-features = false }
```

**Comment by dr-orlovsky** [comment]
@crisdut can you please explain this part:

> Please, configure bp-wallet and bp-esplora as:

I am not getting where to put that strings

**Comment by cryptoquick** [comment]
> @crisdut can you please explain this part:
> 
> > Please, configure bp-wallet and bp-esplora as:
> 
> I am not getting where to put that strings

They just go into the Cargo.toml, replacing the existing entries for bp-wallet and bp-esplora.

**Comment by crisdut** [comment]
Hi @dr-orlovsky 

Would you like some help with this PR?

**Comment by dr-orlovsky** [comment]
@crisdut yeah, that would be much appreciated since I still do not get what specifically have to be done

**Comment by dr-orlovsky** [comment]
This PR got a mix of features, and a couple of merges of other PRs for the changes which should went into the `master` and not here. Thus, I split it into topic-/feature-related PRs and close it for now.

1. Fix for Opret invalidly merged here from https://github.com/RGB-WG/rgb/pull/112 went to https://github.com/RGB-WG/rgb/pull/130 and merged to master
2. A separate PR addressing all electrum-specific changes has cherry-picked all related commits from here: https://github.com/RGB-WG/rgb/pull/131

**Pull request closed without merging**
